import "./base/datatype"
import "./enum/enum"
import "./interface/interface"
import "./function/function"
import "./class/class"
import "./class-interface/class-interface"
import "./generics/generics"